# =============================================================================
# Minimal Starship Prompt Configuration (Bash-like)
# =============================================================================

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Compact single-line prompt (no blank line between prompts)
add_newline = false

# Custom format for a bash-like prompt: hostname:directory [git_info] ➜
format = """
$hostname\
$directory\
$git_branch\
$git_status\
$character"""

# =============================================================================
# Core Components
# =============================================================================

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

[hostname]
ssh_only = false
format = "[$hostname](bold red)"
trim_at = "."
disabled = false

[directory]
style = "cyan bold"
read_only = " 🔒"
truncation_length = 4
truncate_to_repo = false
format = ":[$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = ""
truncation_length = 20
truncation_symbol = "…"
style = "bold green"
format = "[$symbol$branch]($style)"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold green"
conflicted = "!"
up_to_date = ""
untracked = "?"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "$"
modified = "M"
staged = "+"
renamed = "R"
deleted = "D"

# =============================================================================
# Disable verbose modules for minimal prompt
# =============================================================================

[username]
disabled = true

[time]
disabled = true

[memory_usage]
disabled = true

[aws]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[package]
disabled = true

[conda]
disabled = true

[battery]
disabled = true

[cmd_duration]
disabled = true

[jobs]
disabled = true
