# =============================================================================
# Starship Prompt Configuration - SINGLE LINE VERSION
# =============================================================================
# Single-line prompt with essential info only
# Use 'prompt-single' to activate this configuration

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# No blank line between shell prompts
add_newline = false

# Single line format: directory git_info ➜
format = """
$directory\
$git_branch\
$git_status\
$character"""

# =============================================================================
# Directory Configuration - Single Line
# =============================================================================

[directory]
style = "cyan bold"
read_only = " 🔒"
truncation_length = 3
truncate_to_repo = true
format = "[$path]($style)[$read_only]($read_only_style) "

# =============================================================================
# Git Configuration - Single Line
# =============================================================================

[git_branch]
symbol = " "
truncation_length = 15
style = "purple"
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "yellow"
conflicted = "!"
up_to_date = "✓"
untracked = "?"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
stashed = "$"
modified = "M"
staged = "+"
renamed = "R"
deleted = "D"

# =============================================================================
# Character Configuration
# =============================================================================

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

# =============================================================================
# Disable All Other Modules
# =============================================================================

[time]
disabled = true

[username]
disabled = true

[hostname]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[java]
disabled = true

[docker_context]
disabled = true

[kubernetes]
disabled = true

[aws]
disabled = true

[memory_usage]
disabled = true

[cmd_duration]
disabled = true

[battery]
disabled = true

[package]
disabled = true

[conda]
disabled = true

[jobs]
disabled = true
